### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by chacham2**
minor changes and clarifications. 
removed redundant line breaks

### CODE REVIEW

**Comment by mrpmorris** [comment]
I like the line breaks because they fit on my screen nicely. I have a fair large font because my eyes aren't great, and I don't like line-wraps.

**Comment by chacham2** [comment]
I see. It's just that the line breaks mean do nothing and thus might confuse other contributors that think they are there for a reason. Anyway, it also added a missing closing parens, and fixed other little issues with the text, such as where it isn't in line with the latest release.

---

I want to thank you for the site, but as i read further and further it became more and more out of sync with the latest version and with itself. So, i stopped reading it. That being said, the first few pages were really helpful in getting an understanding of Blazor, and i just really want to say thank you for it.

Thank you!

**Comment by mrpmorris** [comment]
I've not revisited it since Blazor 3.1 was released so I can understand parts are out of sync with V7.

I'm surprised though that you say it is out of sync with itself, what do you mean?

If you'd like to resubmit with just the errors fixed, I'll gratefully receive the changes :)

**Comment by chacham2** [comment]
>I'm surprised though that you say it is out of sync with itself, what do you mean?

I was trying to follow the examples in order and things did not seem right. Also, the versions changed between the pages.

>If you'd like to resubmit with just the errors fixed, I'll gratefully receive the changes :)

I've moved elsewhere at this point. But, you gave me a good foundation in how to view the beginnings. So, thank you.

**Pull request closed without merging**
